### ISSUE TITLE
FYI I made of fork of this

### ISSUE THREAD

**Issue by svermeulen** [HiPhish/gradle.nvim#1]
Just chiming in to say that I forked this and changed a few things for my purposes here:

https://github.com/svermeulen/gradle.nvim

I'm not sure what the API is going to look like eventually, but I do have the immediate desire to choose a task from a popup list, so I just did the minimum changes necessary for that.  I also changed it to lazily auto-install the first time it is called, instead of initializing in the plugin folder every time vim starts up.

I have this hooked up to vim-clap and can now just hit a few key strokes to choose and execute a gradle task  :D   Thank you for your work here

![image](https://user-images.githubusercontent.com/810762/82161773-707aeb00-9854-11ea-99a3-a8b973dea106.png)

**Comment by HiPhish** [comment]
Good luck with it. I currently lack the time and energy for this, and it's nor particularly urgent for me as long as I can use the terminal, but I definitely want to make this actually useful. The next hurdle will be to make it responsible so I can collect feedback from Gradle while a task is running instead of having to block until it is all done.

> I'm not sure what the API is going to look like eventually

I plan on having different layers. The topmost layer would be regular Neovim integration which uses the features provided by Neovim, such as the quickfix list. This is what any Vim user will be able to use to get things done out of the box. Maybe not the fanciest interface, but one that works. The next layer would be a Vim Script or Lua interface which exposes the functions and variables used by the top layer. People who like hacking on Neovim could then use those functions to integrate with various plugins like FZF to really get the most out of it.

> I also changed it to lazily auto-install the first time it is called, instead of initializing in the plugin folder every time vim starts up.

Yes, that is something that definitely needs to be done before the plugin is production ready. I just didn't bother with it because it's still experimental and I want to make things work at all first before making the work well.

**Comment by HiPhish** [comment]
Closing the issue since it's not really an issue, but feel free to comment if you have anything else to say.

**Comment by svermeulen** [comment]
Yeah, I just mostly created this issue to say thanks for starting this project, and also to point to my fork in case there's anything useful that can be scavenged there from anyone interested, since I'll probably keep hacking on it as well

I'm trying to figure out what would be useful to do next beyond just providing the task names.  It sounds like you intend to actually execute allow executing tasks and then provide some async feedback of the task progress.  That does sound pretty cool.  At the moment I'm just firing up a terminal that runs the task there.  I'll keep an eye on this repo, thanks again

**Comment by HiPhish** [comment]
>  It sounds like you intend to actually execute allow executing tasks and then provide some async feedback of the task progress

Yes, that and running tests and getting feedback right in Neovim, if it is feasible. I'm getting sick of having to open the test report in Lynx. Who thought that HTML as the only output format was a good choice?

**Comment by JamyGolden** [comment]
@svermeulen why not contribute to this project instead of forking? (I know this is an old issue)

> I plan on having different layers

@HiPhish could you add those goals as checklist items to the readme and a bit of info about contributing? As someone who would potentially contribute, I don't know where to start without speaking to you about your plans.

**Comment by HiPhish** [comment]
@svermeulen This project is effectively dead. I created it when I was still a Java developer and I still think it was a good idea, but a few months later I moved to a different job. I don't need this plugin any longer, so if someone wants to take over he's best off forking it. I should probably add a note in the README that the project is dead.

**Comment by svermeulen** [comment]
I actually don't use this or my fork anymore so would not be the right person to maintain it

@JamyGolden That's fair.  Mostly I just didn't have time to make a proper MR but also wanted to link to some of the work I did on this in case it was useful to anyone else
